name: Update GitHub Stats Cards

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:         # manual trigger
  push:
    branches: [ main ]       # optional: also refresh on pushes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare assets dir
        run: mkdir -p assets

      - name: Fetch Stats card
        run: |
          curl -sSfL \
            -H "User-Agent: gh-actions" \
            "https://github-readme-stats.vercel.app/api?username=Dumidu1212&show_icons=true&theme=radical&include_all_commits=true&count_private=true&hide_border=true&cache_seconds=86400&token=${{ secrets.GH_STATS_TOKEN }}" \
            -o assets/gh-stats.svg

      - name: Fetch Top Languages card
        run: |
          curl -sSfL \
            -H "User-Agent: gh-actions" \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=Dumidu1212&layout=compact&theme=radical&hide_border=true&langs_count=10&cache_seconds=86400&token=${{ secrets.GH_STATS_TOKEN }}" \
            -o assets/top-langs.svg

      - name: Commit changes (only if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(stats): refresh GitHub cards"
          file_pattern: "assets/*.svg"
